run:
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
output:
  sort-results: true